apiVersion: v1
kind: Secret
metadata:
  name: splitwise-secrets
type: Opaque
stringData:
  JWT_SECRET: "Password@256"
  DATABASE_URL: "postgresql://kavyan2:password123@postgres-service:5432/splitwise"
  POSTGRES_PASSWORD: "password123"